### ISSUE TITLE
Problems with Firefox and Opera

### ISSUE THREAD

**Issue by kirat68** [Molorius/WebSockets-ESP-IDF#1]
hello there,
first of all thank you for these nice peaces of code. Had to correct some stuff to get it work with Firefox and Opera. Here the changes I had to made:
* Firefox: in function http_serve had to check the buffer against "Connection: keep-alive, Upgrade". That is what Firefox is sending. Your code is checking against "Connection: Upgrade"

* Opera: opera was not handshaking and complaining about no response to a non empty Sec-WebSocket-Protocol. I was sending in fact a Sec-WebSocket-Protocol. Had to correct your code by adding the response:
	const char WS_RSP[] = "HTTP/1.1 101 Switching Protocols\r\n"
			"Upgrade: websocket\r\n"
			"Connection: Upgrade\r\n"
------>>>>"Sec-WebSocket-Protocol: esp-idf\r\n"
			"Sec-WebSocket-Accept: %s\r\n\r\n";
Hope this wiil help to improve you code.
I am using it in a ESP32 esp-idf eclipse c++ .

**Comment by Molorius** [comment]
Thanks for the tip (I did all testing in Chrome). Submit a pull request if you want your name on the project, otherwise I'll fix it in the next few days.

**Comment by Molorius** [comment]
I fixed the Firefox compatibility in commit https://github.com/Molorius/WebSockets-ESP-IDF/commit/434b47c2d0c72139dc46d9ff96980235de7c1668. I could not replicate your other problem in Opera 52.0.

**Comment by kirat68** [comment]
Regarding Opera. Did you sent a Sec-WebSocket-Protocol?
Here is my connection code that was causing an issue:
webSocketConnection = new WebSocket('ws://192.168.1.1', [ 'esp-idf' ]);

Seems to be that Opera need a response in the header send from the server. When adding
"Sec-WebSocket-Protocol: esp-idf\r\n" as described in the issue, Opera stopped complaining.

**Comment by Molorius** [comment]
I did not use the Sec-WebSocket-Protocol, please specify if you use code outside of what is in the example. I will add in another connection function later to use this functionality.

**Comment by Molorius** [comment]
I added a new function to add a client with the Sec-WebSocket-Protocol header: `ws_server_add_client_protocol`. It is the same as the regular `ws_server_add_client` function, but takes an additional argument to add a protocol. See the documentation on how to use it. I did not add it to the example. 

Please verify that this fixes your issue so I can close this.
