### ISSUE TITLE
Websocket server not parsing frames sent from Firefox

### ISSUE THREAD

**Issue by kirat68** [Molorius/WebSockets-ESP-IDF#2]
This is a bigger issue. The server is not able to receive frames send from Firefox when the frame langth exceeds 1000 bytes. Checked the issue with wireshark. Firefox at least the version I am using (59.0.1) is send the wbsocket frame in 2 different TCP packets. The header in the first packet. The payload in the second. Chrome and Opera are not behaving like this an send the frame in one TCP packet.

After diving in TCP and websocket using wireshark, I understood that the browsers can split the websocket frames in any form. If you send just one frame with a length < 1000 bytes no problem. As soon you try to send multiple frames, TCP will segment the websocket frames at any ws_frame position.

I do not know if you are aware of this limitation and if you want your server to handle this cases. Bigger redesign of ws_frame handling needed.

**Comment by Molorius** [comment]
I wrote this code to handle multiple frames, but I did not test it. This is larger than the intended use case for this server (I have been sending less than 100 bytes typically). I will try to fix it, but it is not a high priority for me at the moment.

**Comment by Molorius** [comment]
@kirat68 I was able to solve the problem, see the external component: https://github.com/Molorius/esp32-websocket

I am surprised that you were able to receive messages that large, as the code before was not working properly. It was only able to send messages up to 146 bytes before breaking for me. Either way, it is fixed now. Tested in Chrome and Firefox. Note that the esp32 gets extremely sluggish if you try to send messages larger than ~10,000 bytes, but I could send them pretty reliably if I kept them less than 5,000 bytes. If you need larger than that, consider sending the message in pieces. 

Either way, please test it to make sure that it works for you so I can close this.

**Comment by kirat68** [comment]
Oh sorry did not mention it? Had of course to change your code for my 
use case to achieve this. Needed to transfer up to 1M to perform OTA. 
And yes with esp32 is better to chunk in pieces.

**Comment by Molorius** [comment]
Were you able to confirm that the update fixed the problem though? My tests appeared to work great.

**Comment by kirat68** [comment]
Currently busy on an other project. If I have the opportunity I will 
check and make tests. I was actually interested in an wss version that I 
found in libwesockets. Were are you located? I am in Portugal.

**Comment by Molorius** [comment]
I am closing this because the issue has been resolved. Feel free to email me if you want to discuss other matters.
